spring:
  application:
    name: "http-mqtt-source"
server:
  port: 8383
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true
  api-docs:
    enabled: true
    version: "openapi_3_0"